FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o seed ./cmd/seed/main.go

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/seed .
COPY fixtures/ fixtures/
CMD ["./seed"]
