-- 026_schema_migrations_revoke_dml.up.sql
--
-- Revoke INSERT/UPDATE/DELETE on axiaops.schema_migrations from the app
-- user. schema_migrations is golang-migrate's internal bookkeeping table
-- (version + dirty bit) — application code never reads or writes it; only
-- the migration tooling does, and that runs as axiaops_owner via
-- MIGRATION_DATABASE_URL.
--
-- Why the gap exists at all: schema_migrations is created by
-- migratepg.WithInstance (CREATE TABLE IF NOT EXISTS schema_migrations …)
-- *before* any migration runs, so 000_init's
--
--     GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA axiaops TO axiaops;
--
-- catches it the same way it caught migration_history (closed by 025).
-- Modifying 000_init.up.sql isn't an option (drift detection on every
-- already-applied env), so we revoke here.
--
-- Threat model: a SQL injection that escapes RLS could otherwise
--   - UPDATE schema_migrations SET dirty=true → DoS the deploy pipeline
--     (next boot refuses with "Dirty database version N. Fix and force
--     version.")
--   - UPDATE schema_migrations SET version=99999 → golang-migrate thinks
--     all migrations are applied, real DDL silently stops running, schema
--     drifts behind code.
-- Both are unlikely in practice but unnecessary to leave open.
--
-- Idempotent: REVOKE on a privilege the role doesn't hold is a no-op
-- with a NOTICE.

REVOKE INSERT, UPDATE, DELETE ON axiaops.schema_migrations FROM axiaops;
